import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import  "bootstrap/dist/css/bootstrap.min.css"
import NavBar from './Components/nav/NavBar'
//import ProductLayout from "./Products/layout";
import ProductDetails from "./Products/[Products]/page";
import ProductSearch from "./Products/page";
import styles from './page.module.css'
import Sidebar from "./Components/SideBar/Sidebar";
import Footer from "./Components/Footer/Footer";
import { CartProvider } from "./context/CartContext";
import { Suspense } from "react";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "MY NEXT APP",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" >
      <body style={{backgroundColor:'black'}}>
      <div >
      <NavBar/>
      <div style={{display:"flex"}}>
       <div style={{background:'black',width:'75%'}}>
        <CartProvider>
          <Suspense fallback={<span style={{background:'blue'}}>loding...</span>}>
       {children}
           </Suspense>
       </CartProvider>
       </div>
       <div className={styles.div25}>
       <Sidebar/>
       </div>
       
       </div>
       
      </div>
      
      </body>
      
    </html>
  );
}
